version: '3.8'

services:

  postgres:
    image: postgres:17-alpine
    container_name: pec-postgres
    environment:
      POSTGRES_DB: pec_db
      POSTGRES_USER: pec_admin
      POSTGRES_PASSWORD: pec_password
    ports:
      - "5433:5432"
    volumes:
      - pec_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pec_admin -d pec_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: pec-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pec_postgres_data: